In [1]:
#import libraries and raw retail industry data for india
import pandas as pd
data = pd.read_excel('ind_retail.xlsx')
data.to_csv()
data.head()

,Date,avenue_close,avenue_volume,aditya_close,aditya_volume,vmart_close,vmart_volume,shoppers_close,shoppers_volume,future_close,future_volume,afl_close,afl_volume,trent_close,trent_volume
0,2020-05-14,2323.10,6563,103.05,94070,1589.45,142,159.90,766,80.55,47703,134.75,2510,450.40,4280
1,2020-05-13,2351.75,13576,107.25,82984,1646.60,38,162.05,1244,83.35,122136,133.65,3823,451.00,9394
2,2020-05-12,2300.10,10724,104.05,64742,1638.30,199,161.55,1346,81.80,99507,131.80,503,448.55,10070
3,2020-05-11,2310.45,9972,105.40,61781,1642.10,43,162.85,1155,84.00,1422166,133.00,1389,450.55,7160
4,2020-05-08,2248.85,11759,106.85,41754,1643.95,94,162.85,1306,80.60,281274,132.15,607,460.15,6750

In [2]:
#rename columns for uniformity across datasets
data.rename(columns={'Date':'date'},inplace=True)
data.head()

,date,avenue_close,avenue_volume,aditya_close,aditya_volume,vmart_close,vmart_volume,shoppers_close,shoppers_volume,future_close,future_volume,afl_close,afl_volume,trent_close,trent_volume
0,2020-05-14,2323.10,6563,103.05,94070,1589.45,142,159.90,766,80.55,47703,134.75,2510,450.40,4280
1,2020-05-13,2351.75,13576,107.25,82984,1646.60,38,162.05,1244,83.35,122136,133.65,3823,451.00,9394
2,2020-05-12,2300.10,10724,104.05,64742,1638.30,199,161.55,1346,81.80,99507,131.80,503,448.55,10070
3,2020-05-11,2310.45,9972,105.40,61781,1642.10,43,162.85,1155,84.00,1422166,133.00,1389,450.55,7160
4,2020-05-08,2248.85,11759,106.85,41754,1643.95,94,162.85,1306,80.60,281274,132.15,607,460.15,6750

In [3]:
#update the dataset till 26th May 2020
new_row = {'date':'2020-05-15','avenue_close':2329.45,'aditya_close':104.15, 'vmart_close':1613.65,
           'shoppers_close':159.80, 'future_close':78.4, 'afl_close':132.5, 'trent_close':441.45}
data = data.append(new_row,ignore_index=True)
new_row = {'date':'2020-05-18','avenue_close':2306.00,'aditya_close':100.05, 'vmart_close':1563.25,
           'shoppers_close':139.40, 'future_close':74.5, 'afl_close':120.5, 'trent_close':414.80}
data = data.append(new_row,ignore_index=True)
new_row = {'date':'2020-05-19','avenue_close':2336.25,'aditya_close':102.65, 'vmart_close':1528.30,
           'shoppers_close':134.15, 'future_close':70.85, 'afl_close':121.75, 'trent_close':403.55}
data = data.append(new_row,ignore_index=True)
new_row = {'date':'2020-05-20','avenue_close':2453.05,'aditya_close':102.95, 'vmart_close':1630.55,
           'shoppers_close':133.25, 'future_close':70.90, 'afl_close':113.35, 'trent_close':423.30}
data = data.append(new_row,ignore_index=True)
new_row = {'date':'2020-05-21','avenue_close':2470.50,'aditya_close':112.15, 'vmart_close':1582.75,
           'shoppers_close':132.95, 'future_close':70, 'afl_close':117.65, 'trent_close':451.40}
data = data.append(new_row,ignore_index=True)
new_row = {'date':'2020-05-22','avenue_close':2402.55,'aditya_close':111.10, 'vmart_close':1576.55,
           'shoppers_close':132.90, 'future_close':69.95, 'afl_close':116.75, 'trent_close':442.70}
data = data.append(new_row,ignore_index=True)
new_row = {'date':'2020-05-26','avenue_close':2290.40,'aditya_close':108.35, 'vmart_close':1575.65,
           'shoppers_close':132.80, 'future_close':73.40, 'afl_close':112.70, 'trent_close':459.50}
data = data.append(new_row,ignore_index=True)

In [4]:
data.fillna(0)

,date,avenue_close,avenue_volume,aditya_close,aditya_volume,vmart_close,vmart_volume,shoppers_close,shoppers_volume,future_close,future_volume,afl_close,afl_volume,trent_close,trent_volume
0,2020-05-14 00:00:00,2323.10,6563.0,103.05,94070.0,1589.45,142.0,159.90,766.0,80.55,47703.0,134.75,2510.0,450.40,4280.0
1,2020-05-13 00:00:00,2351.75,13576.0,107.25,82984.0,1646.60,38.0,162.05,1244.0,83.35,122136.0,133.65,3823.0,451.00,9394.0
2,2020-05-12 00:00:00,2300.10,10724.0,104.05,64742.0,1638.30,199.0,161.55,1346.0,81.80,99507.0,131.80,503.0,448.55,10070.0
3,2020-05-11 00:00:00,2310.45,9972.0,105.40,61781.0,1642.10,43.0,162.85,1155.0,84.00,1422166.0,133.00,1389.0,450.55,7160.0
4,2020-05-08 00:00:00,2248.85,11759.0,106.85,41754.0,1643.95,94.0,162.85,1306.0,80.60,281274.0,132.15,607.0,460.15,6750.0
5,2020-05-07 00:00:00,2198.35,6661.0,110.90,98700.0,1650.80,213.0,164.50,7205.0,76.80,324808.0,132.60,246.0,465.45,7609.0
6,2020-05-06 00:00:00,2170.05,11093.0,110.45,415593.0,1649.30,114.0,162.20,10829.0,73.15,63698.0,133.55,839.0,470.55,17469.0
7,2020-05-05 00:00:00,2205.20,6934.0,107.05,61886.0,1673.15,186.0,166.70,3786.0,76.95,73467.0,134.20,1185.0,476.10,63380.0
8,2020-05-04 00:00:00,2284.55,10215.0,109.00,111835.0,1685.55,431.0,176.00,3427.0,80.95,79751.0,134.90,2547.0,477.50,11391.0
9,2020-04-30 00:00:00,2379.80,9159.0,115.70,254801.0,1724.80,682.0,187.35,3396.0,85.20,183978.0,139.00,5728.0,505.05,29029.0
10,2020-04-29 00:00:00,2328.70,7601.0,112.10,310228.0,1715.10,306.0,190.20,4294.0,89.65,912337.0,138.45,1307.0,487.15,9001.0
11,2020-04-28 00:00:00,2301.30,4477.0,115.30,30866.0,1707.80,443.0,188.10,1128.0,92.45,12146.0,137.80,2544.0,491.70,20055.0
12,2020-04-27 00:00:00,2317.80,7818.0,115.85,54228.0,1721.45,240.0,192.15,474.0,97.30,75595.0,140.95,3893.0,493.95,11455.0
13,2020-04-24 00:00:00,2311.40,6704.0,122.30,52995.0,1713.55,195.0,190.20,615.0,102.40,684692.0,144.00,10279.0,486.15,6852.0
14,2020-04-23 00:00:00,2296.45,15180.0,123.95,44596.0,1719.95,412.0,193.85,1863.0,98.40,1582506.0,144.15,258967.0,497.65,23186.0
15,2020-04-22 00:00:00,2292.70,9946.0,122.00,46781.0,1674.05,685.0,190.90,717.0,93.75,53774.0,144.10,3605.0,473.05,8090.0
16,2020-04-21 00:00:00,2237.20,6809.0,127.60,48012.0,1666.90,3837.0,188.95,2032.0,89.30,63265.0,142.05,8776.0,474.10,13659.0
17,2020-04-20 00:00:00,2257.45,11171.0,139.75,31591.0,1729.25,674.0,198.55,2051.0,85.05,12355.0,155.50,7285.0,479.15,21049.0
18,2020-04-17 00:00:00,2211.35,7682.0,143.10,59893.0,1741.35,775.0,199.65,1926.0,81.00,1333473.0,141.40,5012.0,488.25,38328.0
19,2020-04-16 00:00:00,2141.10,15024.0,138.80,49926.0,1637.60,154.0,199.15,556.0,77.15,314039.0,138.80,905.0,460.05,9510.0
20,2020-04-15 00:00:00,2181.90,29877.0,145.50,38057.0,1634.65,283.0,198.00,1674.0,73.50,321693.0,136.90,161107.0,454.35,19180.0
21,2020-04-13 00:00:00,2287.90,10920.0,145.25,30882.0,1620.85,345.0,195.50,1614.0,70.00,603291.0,136.95,5019.0,452.10,28384.0
22,2020-04-09 00:00:00,2408.30,76055.0,149.50,16913.0,1611.60,9398.0,200.35,696.0,66.70,1834884.0,141.45,1994.0,462.65,171374.0
23,2020-04-08 00:00:00,2299.65,49358.0,149.20,18245.0,1589.80,1137.0,198.15,568.0,64.25,35099.0,134.20,1608.0,462.25,21378.0
24,2020-04-07 00:00:00,2191.45,119372.0,149.45,39477.0,1676.25,737.0,194.30,491.0,67.60,35966.0,139.95,1469.0,456.65,21274.0
25,2020-04-03 00:00:00,2087.10,8910.0,146.00,19844.0,1530.80,820.0,191.55,159.0,71.15,13609.0,137.00,1017.0,451.80,32565.0
26,2020-04-01 00:00:00,2092.95,14967.0,150.75,24951.0,1469.45,629.0,193.65,615.0,74.85,10233.0,138.05,2258.0,465.55,27818.0
27,2020-03-31 00:00:00,2200.70,18631.0,153.15,21561.0,1412.50,5163.0,193.45,2054.0,78.75,9960.0,146.00,2529.0,479.20,21704.0
28,2020-03-30 00:00:00,2115.70,22318.0,158.50,33155.0,1444.60,431.0,201.75,2136.0,82.85,13952.0,142.85,2105.0,456.60,19408.0
29,2020-03-27 00:00:00,2083.30,44395.0,166.65,53572.0,1462.55,1252.0,222.25,162.0,87.20,13489.0,150.05,1101.0,484.80,26171.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,2020-01-31 00:00:00,2133.45,185190.0,233.90,27137.0,1988.50,247.0,414.00,145.0,329.65,27659.0,351.62,3818.0,589.75,5847.0
69,2020-01-30 00:00:00,2051.65,142186.0,229.50,16192.0,1986.65,229.0,419.65,299.0,328.35,19136.0,350.13,2128.0,583.15,5391.0
70,2020-01-29 00:00:00,1974.00,33035.0,228.00,19592.0,2010.05,972.0,419.95,636.0,332.50,9134.0,355.09,1340.0,582.30,17528.0
71,2020-01-28 00:00:00,1929.30,11698.0,228.95,14431.0,1937.50,462.0,420.65,1860.0,333.35,21088.0,353.51,2027.0,589.60,18308.0
72,2020-01-27 00:00:00,1952.60,18078.0,233.70,11880.0,1974.05,15785.0,421.00,924.0,336.15,45434.0,364.66,2789.0,571.50,6310.0
73,2020-01-24 00:00:00,1949.75,22541.0,234.75,12915.0,1969.05,1158.0,418.00,2775.0,334.10,1346397.0,364.80,738.0,583.35,16078.0
74,2020-01-23 00:00:00,1927.00,42197.0,233.90,24882.0,1927.10,1138.0,414.00,250731.0,340.45,18447.0,370.26,2458.0,589.35,5461.0
75,2020-01-22 00:00:00,1914.20,18490.0,235.10,8732.0,1878.35,315842.0,416.05,1845.0,343.50,70003.0,375.95,6867.0,587.45,7134.0
76,2020-01-21 00:00:00,1916.85,30897.0,229.85,12486.0,1889.05,2034.0,426.70,21713.0,343.20,19291.0,374.95,1225.0,592.95,5440.0
77,2020-01-20 00:00:00,1936.80,72536.0,230.85,31635.0,1871.90,837.0,412.55,256751.0,348.95,35103.0,361.46,2200.0,599.65,18009.0
78,2020-01-17 00:00:00,1989.60,63877.0,235.70,15530.0,1838.40,3403.0,411.15,2538.0,350.50,38057.0,363.89,1448.0,589.60,21706.0
79,2020-01-16 00:00:00,1947.40,39699.0,237.30,23919.0,1724.50,591.0,402.20,253286.0,349.00,41071.0,360.37,868.0,590.25,27687.0
80,2020-01-15 00:00:00,1933.20,47955.0,231.30,35843.0,1700.20,93902.0,406.65,8640.0,345.25,244343.0,359.88,2284.0,584.05,30530.0
81,2020-01-14 00:00:00,1930.00,57461.0,232.90,36554.0,1655.50,286.0,391.90,526.0,350.50,35162.0,363.40,973.0,560.30,7715.0
82,2020-01-13 00:00:00,1905.95,3278899.0,230.35,91842.0,1660.75,416.0,390.55,1111.0,348.45,47839.0,361.95,2258.0,545.10,20505.0
83,2020-01-10 00:00:00,1876.75,60533.0,233.35,27425.0,1663.45,114.0,384.25,48595.0,351.15,27388.0,363.22,2934.0,550.75,9685.0
84,2020-01-09 00:00:00,1882.85,6955515.0,240.00,26739.0,1678.10,27.0,381.55,34.0,354.85,102991.0,358.48,4901.0,547.25,8054.0
85,2020-01-08 00:00:00,1829.50,21931.0,235.95,17737.0,1671.30,89.0,377.10,805.0,353.05,30642.0,361.10,986.0,531.65,523304.0
86,2020-01-07 00:00:00,1815.15,23983.0,232.60,13463.0,1671.55,55496.0,370.00,2818.0,345.25,63208.0,358.97,1046.0,531.65,8656.0
87,2020-01-06 00:00:00,1789.65,35175.0,234.50,23404.0,1660.10,146.0,369.25,418.0,336.05,71615.0,356.81,4075.0,529.95,11918.0
88,2020-01-03 00:00:00,1842.70,204124.0,240.10,24094.0,1676.85,191.0,375.65,1724.0,334.55,36904.0,365.25,2490.0,535.80,12255.0
89,2020-01-02 00:00:00,1822.60,31383.0,240.55,55637.0,1664.20,336.0,371.95,5488.0,331.80,33267.0,357.85,2620.0,541.00,8654.0
90,2020-01-01 00:00:00,1827.00,29843.0,233.80,14242.0,1658.80,93.0,370.35,20.0,342.15,27471.0,360.51,4583.0,529.75,9191.0
91,2020-05-15,2329.45,0.0,104.15,0.0,1613.65,0.0,159.80,0.0,78.40,0.0,132.50,0.0,441.45,0.0
92,2020-05-18,2306.00,0.0,100.05,0.0,1563.25,0.0,139.40,0.0,74.50,0.0,120.50,0.0,414.80,0.0
93,2020-05-19,2336.25,0.0,102.65,0.0,1528.30,0.0,134.15,0.0,70.85,0.0,121.75,0.0,403.55,0.0
94,2020-05-20,2453.05,0.0,102.95,0.0,1630.55,0.0,133.25,0.0,70.90,0.0,113.35,0.0,423.30,0.0
95,2020-05-21,2470.50,0.0,112.15,0.0,1582.75,0.0,132.95,0.0,70.00,0.0,117.65,0.0,451.40,0.0
96,2020-05-22,2402.55,0.0,111.10,0.0,1576.55,0.0,132.90,0.0,69.95,0.0,116.75,0.0,442.70,0.0
97,2020-05-26,2290.40,0.0,108.35,0.0,1575.65,0.0,132.80,0.0,73.40,0.0,112.70,0.0,459.50,0.0

In [5]:
data.dtypes

date                object
avenue_close       float64
avenue_volume      float64
aditya_close       float64
aditya_volume      float64
vmart_close        float64
vmart_volume       float64
shoppers_close     float64
shoppers_volume    float64
future_close       float64
future_volume      float64
afl_close          float64
afl_volume         float64
trent_close        float64
trent_volume       float64
dtype: object

In [6]:
#index calculation
data['initial_calc_index'] = (((data['avenue_close'])*(data['avenue_volume'])+(data['aditya_close'])*(data['aditya_volume'])
                       +(data['vmart_close'])*(data['vmart_volume'])+(data['shoppers_close'])*(data['shoppers_volume'])
                       +(data['future_close'])*(data['future_volume'])+(data['afl_close'])*(data['afl_volume'])
                       +(data['trent_close'])*(data['trent_volume']))
                      /(data['avenue_volume']+data['aditya_volume']+data['vmart_volume']
                        +data['shoppers_volume']+data['future_volume']+data['afl_volume']+data['trent_volume']))
data['initial_calc_index'] = data['initial_calc_index'].round(2)
data['calc_index'] = (((data['avenue_close'])*(647.775)+(data['aditya_close'])*(773.948)
                       +(data['vmart_close'])*(18.156)+(data['shoppers_close'])*(87.99)
                       +(data['future_close'])*(527.398)+(data['afl_close'])*(78.655)
                       +(data['trent_close'])*(355.487))
                      /(647.775+773.948+18.156+87.99+527.398+78.655+355.487))
data['calc_index'] = data['calc_index'].round(2)
data.head()

,date,avenue_close,avenue_volume,aditya_close,aditya_volume,vmart_close,vmart_volume,shoppers_close,shoppers_volume,future_close,future_volume,afl_close,afl_volume,trent_close,trent_volume,initial_calc_index,calc_index
0,2020-05-14 00:00:00,2323.10,6563.0,103.05,94070.0,1589.45,142.0,159.90,766.0,80.55,47703.0,134.75,2510.0,450.40,4280.0,201.22,739.42
1,2020-05-13 00:00:00,2351.75,13576.0,107.25,82984.0,1646.60,38.0,162.05,1244.0,83.35,122136.0,133.65,3823.0,451.00,9394.0,240.22,749.32
2,2020-05-12 00:00:00,2300.10,10724.0,104.05,64742.0,1638.30,199.0,161.55,1346.0,81.80,99507.0,131.80,503.0,448.55,10070.0,238.76,734.07
3,2020-05-11 00:00:00,2310.45,9972.0,105.40,61781.0,1642.10,43.0,162.85,1155.0,84.00,1422166.0,133.00,1389.0,450.55,7160.0,101.54,738.05
4,2020-05-08 00:00:00,2248.85,11759.0,106.85,41754.0,1643.95,94.0,162.85,1306.0,80.60,281274.0,132.15,607.0,460.15,6750.0,166.30,723.10

In [7]:
#save the file in csv format
data.to_csv('ind_retail_final.csv')

In [8]:
data.tail(7)

,date,avenue_close,avenue_volume,aditya_close,aditya_volume,vmart_close,vmart_volume,shoppers_close,shoppers_volume,future_close,future_volume,afl_close,afl_volume,trent_close,trent_volume,initial_calc_index,calc_index
91,2020-05-15,2329.45,NaN,104.15,NaN,1613.65,NaN,159.80,NaN,78.40,NaN,132.50,NaN,441.45,NaN,NaN,739.78
92,2020-05-18,2306.00,NaN,100.05,NaN,1563.25,NaN,139.40,NaN,74.50,NaN,120.50,NaN,414.80,NaN,NaN,726.31
93,2020-05-19,2336.25,NaN,102.65,NaN,1528.30,NaN,134.15,NaN,70.85,NaN,121.75,NaN,403.55,NaN,NaN,732.21
94,2020-05-20,2453.05,NaN,102.95,NaN,1630.55,NaN,133.25,NaN,70.90,NaN,113.35,NaN,423.30,NaN,NaN,765.97
95,2020-05-21,2470.50,NaN,112.15,NaN,1582.75,NaN,132.95,NaN,70.00,NaN,117.65,NaN,451.40,NaN,NaN,776.97
96,2020-05-22,2402.55,NaN,111.10,NaN,1576.55,NaN,132.90,NaN,69.95,NaN,116.75,NaN,442.70,NaN,NaN,757.64
97,2020-05-26,2290.40,NaN,108.35,NaN,1575.65,NaN,132.80,NaN,73.40,NaN,112.70,NaN,459.50,NaN,NaN,730.59